name: Work 2 Erick
on: [push]
  push:
      branches:
        - test_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Impresion 1
      run: echo "Hola Pitaya!"
    - name: Impresion 2
      run: echo "Que hace"
    - name: Impresion 3
      run: echo "Pa terminar"